#!/usr/bin/env node
/**
 * Bakes the pixel art into the plugin.
 *
 * BRAT only ever downloads main.js, manifest.json and styles.css from a
 * release, so a plugin cannot ship a folder of PNGs the way the Electron app
 * did. This script turns assets/ into a TypeScript module of base64 strings
 * and folds the web font into styles.css as a data URI.
 *
 * Run via `npm run assets` (the build and dev scripts do it for you).
 */
import { readdirSync, readFileSync, statSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');
const assetsRoot = join(repoRoot, 'assets');
const outFile = join(repoRoot, 'src', 'assets', 'assetData.ts');

const TEXT_ASSETS = ['default-layout.json', join('furniture', 'furniture-catalog.json')];
const FONT_FILE = join('font', 'FSPixelSansUnicode-Regular.woff2');

function walk(dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...walk(full));
    else out.push(full);
  }
  return out;
}

/** Asset keys always use forward slashes — they must match furniture-catalog.json. */
function keyOf(fullPath) {
  return relative(assetsRoot, fullPath).split(sep).join('/');
}

const files = walk(assetsRoot).sort();

const pngEntries = [];
for (const file of files) {
  if (!file.endsWith('.png')) continue;
  pngEntries.push([keyOf(file), readFileSync(file).toString('base64')]);
}

const textEntries = [];
for (const rel of TEXT_ASSETS) {
  const full = join(assetsRoot, rel);
  // Re-serialize to drop indentation we would otherwise ship in the bundle.
  const compact = JSON.stringify(JSON.parse(readFileSync(full, 'utf-8')));
  textEntries.push([keyOf(full), compact]);
}

const banner = `// AUTO-GENERATED by scripts/gen-assets.mjs — do not edit by hand.
// Source of truth is the assets/ folder; run \`npm run assets\` to regenerate.
`;

const body = [
  banner,
  '/** Every sprite sheet, base64-encoded, keyed by its path inside assets/. */',
  'export const ASSET_PNG_BASE64: Record<string, string> = {',
  ...pngEntries.map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`),
  '};',
  '',
  '/** JSON assets, already minified. */',
  'export const ASSET_TEXT: Record<string, string> = {',
  ...textEntries.map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`),
  '};',
  '',
].join('\n');

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, body, 'utf-8');

// ── styles.css ────────────────────────────────────────────────────────────
const cssTemplate = readFileSync(join(repoRoot, 'src', 'styles.src.css'), 'utf-8');
const fontBase64 = readFileSync(join(assetsRoot, FONT_FILE)).toString('base64');
const css = cssTemplate.replace('__FONT_WOFF2_BASE64__', fontBase64);
if (css === cssTemplate) {
  throw new Error('styles.src.css no longer contains the __FONT_WOFF2_BASE64__ placeholder');
}
writeFileSync(join(repoRoot, 'styles.css'), css, 'utf-8');

const pngBytes = pngEntries.reduce((sum, [, v]) => sum + v.length, 0);
console.log(
  `[assets] ${pngEntries.length} sprites (${(pngBytes / 1024).toFixed(0)} KB base64), ` +
  `${textEntries.length} JSON assets, font ${(fontBase64.length / 1024).toFixed(0)} KB base64`,
);
